CREATE TABLE CARCASE_TYPE (
    CARCASE_TYPE_ID INT NOT NULL PRIMARY KEY,
    CARCASE_TYPE_NAME VARCHAR(64)
);

CREATE TABLE CARCASE (
    CARCASE_ID INT NOT NULL PRIMARY KEY,
    CARCASE_SERIAL_NUMBER VARCHAR(64),
    COLOR VARCHAR(64),
    DOOR_COUNT INT,
    CARCASE_TYPE_ID INT NOT NULL,
    UNIQUE (CARCASE_SERIAL_NUMBER),
    FOREIGN KEY (CARCASE_TYPE_ID)
        REFERENCES CARCASE_TYPE (CARCASE_TYPE_ID)
);

CREATE TABLE TRANSMISSION_TYPE (
    TRANSMISSION_TYPE_ID INT NOT NULL PRIMARY KEY,
    TRANSMISSION_TYPE_NAME VARCHAR(64)
);

CREATE TABLE TRANSMISSION (
    TRANSMISSION_ID INT NOT NULL PRIMARY KEY,
    TRANSMISSION_SERIAL_NUMBER VARCHAR(64),
    TRANSMISSION_TYPE_ID INT NOT NULL,
    UNIQUE (TRANSMISSION_SERIAL_NUMBER),
    FOREIGN KEY (TRANSMISSION_TYPE_ID)
        REFERENCES TRANSMISSION_TYPE (TRANSMISSION_TYPE_ID)
);

CREATE TABLE ENGINE_TYPE (
    ENGINE_TYPE_ID INT NOT NULL PRIMARY KEY,
    ENGINE_TYPE_NAME VARCHAR(64)
);

CREATE TABLE ENGINE (
    ENGINE_ID INT NOT NULL PRIMARY KEY,
    ENGINE_SERIAL_NUMBER VARCHAR(64),
    CAPACITY FLOAT,
    POWER FLOAT,
    ENGINE_TYPE_ID INT NOT NULL,
    UNIQUE (ENGINE_SERIAL_NUMBER),
    FOREIGN KEY (ENGINE_TYPE_ID)
        REFERENCES ENGINE_TYPE (ENGINE_TYPE_ID)
);

CREATE TABLE CAR_PARK (
    CAR_ID INT NOT NULL PRIMARY KEY,
    NAME VARCHAR(64),
    CARCASE_ID INT NOT NULL,
    ENGINE_ID INT NOT NULL,
    TRANSMISSION_ID INT NOT NULL,
    FOREIGN KEY (CARCASE_ID)
        REFERENCES CARCASE (CARCASE_ID),
    FOREIGN KEY (ENGINE_ID)
        REFERENCES ENGINE (ENGINE_ID),
    FOREIGN KEY (TRANSMISSION_ID)
        REFERENCES TRANSMISSION (TRANSMISSION_ID)
);

INSERT INTO CARCASE_TYPE VALUES(1, "Sedan");

INSERT INTO ENGINE_TYPE VALUES(1, "Petrol");

INSERT INTO TRANSMISSION_TYPE VALUES(1, "Mechanical");

INSERT INTO CARCASE VALUES(1, "45dfdf", "RED", 4, 1);

INSERT INTO ENGINE VALUES(1, "engine456", 123.3, 2.4, 1);
INSERT INTO TRANSMISSION VALUES(1, "transm453", 1);
INSERT INTO CAR_PARK VALUES(1, "Mazda", 1, 1, 1);

COMMIT;
